package rain.db;



/**
 * Student generated by MyEclipse - Hibernate Tools
 */

public class Student  implements java.io.Serializable {


    // Fields    

     private Integer studentId;
     private String studentName;
     private String studentClass;


    // Constructors

    /** default constructor */
    public Student() {
    }

    
    /** full constructor */
    public Student(String studentName, String studentClass) {
        this.studentName = studentName;
        this.studentClass = studentClass;
    }

   
    // Property accessors

    public Integer getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    public String getStudentName() {
        return this.studentName;
    }
    
    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getStudentClass() {
        return this.studentClass;
    }
    
    public void setStudentClass(String studentClass) {
        this.studentClass = studentClass;
    }
   








}